//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BusBooking
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "No of Seats")]
        public string NoOfSeats { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Status { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public System.DateTime DateTime { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int LoginId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int BusId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int BusRoutesId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Bus Bus { get; set; }
        public virtual BusRoutes BusRoute { get; set; }
    }
}
