//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusModelContainer : DbContext
    {
        public BusModelContainer()
            : base("name=BusModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<LoginRoles> LoginRoles { get; set; }
        public virtual DbSet<BusBooking> BusBookings { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusRoutes> BusRoutes { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
    }
}
