//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BusRoutes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusRoutes()
        {
            this.BusBookings = new HashSet<BusBooking>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Depature { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Arrival { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Departure Date Time")]
        public System.DateTime DepatureDataTime { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="Arrival Date Time")]
        public System.DateTime ArrivalDateTime { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Price { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int BusId { get; set; }

        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusBooking> BusBookings { get; set; }
    }
}
