//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="Driver Name")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="Contact No")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int BusId { get; set; }

        public virtual Bus Bus { get; set; }
    }
}
