//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginRoles
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This field is required")]

        public string Role { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public int LoginId { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
